library(shinythemes)
library(shinyjs)
library(httr)
library(lubridate)
options(stringsAsFactors = FALSE)

dataPath <- paste0(getwd(),"/www")
functionsPath <- paste0(dataPath,"/functions")
initPath <- getwd()

if(!dir.exists(file.path(initPath, "answers"))) dir.create(file.path(initPath, "answers")) 
if(!dir.exists(file.path(initPath, "usersProgress"))) dir.create(file.path(initPath, "usersProgress")) 

setwd(dataPath)
endSettings <<- read.csv("endSettings.csv", encoding = "UTF-8", strip.white = T)
setwd(initPath)

source(paste0(functionsPath,"/readFromURL.R"))
source(paste0(functionsPath,"/startApp.R"))
source(paste0(functionsPath,"/readNormsFile.R"))
source(paste0(functionsPath,"/callSW.R"))
source(paste0(functionsPath,"/addSidebarObservers.R"))
source(paste0(functionsPath,"/addDataSaving.R"))
source(paste0(functionsPath,"/renderType.R"))
source(paste0(functionsPath,"/renderCategory.R"))
source(paste0(functionsPath,"/renderInput.R"))
source(paste0(functionsPath,"/badDate.R"))
source(paste0(functionsPath,"/countScore.R"))